name: Pull Request
on:
  pull_request:
    types: [opened]
permissions:
    contents: none
    pull-requests: write

jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        # ref: https://github.com/technote-space/assign-author/releases/tag/v1.6.1
        uses: technote-space/assign-author@8b6e94ed5cc9ca75ad16dba280945e23b1b4e854
