name: deploy app distribution
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      feature_1:
        description: "feature 1"
        required: false
        default: false
        type: boolean

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: "build step"
        run: |
          echo ${{ github.event.inputs.feature_1 }}
      - name: set
        id: vars
        run: |
          echo ::set-output name=html::$(cat << EOS
          <table>
          <tr>
          <td>Firebase Version</td>
          <td>hogehoge</td>
          </tr>
          </table>
          EOS
          )
      - uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: "Result Dashboard"
          head_sha: ${{ github.sha }}
          conclusion: "success"
          status: "completed"
          output: |
            title: Summary
            summary: ${{ steps.vars.outputs.html }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        if: ${{ github.event.issue.pull_request }}
        id: comment
        with:
          route: POST ${{ github.event.issue.comments_url }}
          body: ${{ toJSON(env.REQUEST_BODY) }}
        env:
          REQUEST_BODY: |
            Multi-line string with *special* characters:
            - "'`
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
