name: ktlintCheck
on:
  workflow_call:
permissions:
  contents: read
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: ktlintCheck
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
      - name: ktlintFormat
        if: ${{ failure() }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintFormat
      - name: set
        if: ${{ failure() }}
        id: vars
        run: |
          echo ::set-output name=annotations::$(.github/workflows/script/diff_annotations.kts)
      - name: ktlint check-runs
        if: ${{ failure() }}
        uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: ktlint
          head_sha: ${{ github.sha }}
          conclusion: "success"
          status: "failure"
          annotations: ${{ steps.vars.outputs.annotations }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}