name: deploy app distribution
on:
  workflow_call:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: assembleFirebaseRelease
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleFirebaseRelease -x lint
      - name: appDistributionUploadFirebaseRelease
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease
