name: deploy app distribution
on:
  workflow_call:
    inputs:
      BRANCH_NAME:
        default: 'develop'
        required: false
        type: string

jobs:
  dispatch_only:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: |
          echo "test"
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: "build step"
        run: |
          echo "=====BRANCH_NAME====="
          echo ${{ github.inputs.BRANCH_NAME }}
      - name: set
        id: vars
        run: |
          echo $(cat HTML<<EOS
          <table>
          <tr>
          <td>Firebase Version</td>
          <td>hogehoge</td>
          </tr>
          </table>
          EOS
          ) >> $GITHUB_ENV
      - uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: "Result Dashboard"
          head_sha: ${{ github.sha }}
          conclusion: "success"
          status: "completed"
          output: |
            title: Summary
            summary: ${{ env.HTML }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        if: ${{ github.event.issue.pull_request }}
        id: comment
        with:
          route: POST ${{ github.event.issue.comments_url }}
          body: ${{ toJSON(env.REQUEST_BODY) }}
        env:
          REQUEST_BODY: |
            Multi-line string with *special* characters:
            - "'`
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
