name: ktlintCheck
on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ (github.event.pull_request.head.sha != null && github.event.pull_request.head.sha) || github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: ktlintCheck
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
      - name: ktlintFormat
        if: ${{ failure() }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintFormat
      - name: Cache main.kts
        if: ${{ always() }}
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/main.kts.compiled.cache
          key: ${{ hashFiles('**/*.main.kts') }}
      - name: set
        if: ${{ failure() }}
        id: vars
        run: |
          echo ::set-output name=annotations::$(.github/workflows/script/diff_annotations.main.kts)
          echo ::set-output name=xml::$(find . -type f -path './build/reports/ktlint/*.xml' | xargs cat)
      - name: ktlint check-runs
        if: ${{ failure() }}
        uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: "ktlint check-runs"
          head_sha: ${{ env.SHA }}
          conclusion: "failure"
          status: "completed"
          output: |
            title: "Ktlint"
            summary: ${{ toJson(steps.vars.outputs.annotations) }}
            annotations: ${{ steps.vars.outputs.annotations }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
