name: ktlintCheck
on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: ktlintCheck
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
      - name: ktlintFormat
        if: ${{ failure() }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintFormat
      - name: set diff
        if: ${{ failure() }}
        id: vars
        run: |
          start=$(date +%s)
          result=$(.github/workflows/script/diff_annotations.main.kts)
          end=$(date +%s)
          echo $result
          
          
          start=$(date +%s)
          result=$(.github/workflows/script/diff_annotations.main.kts)
          end=$(date +%s)
          
          echo "second time
          echo $end - $start
          
          echo ::set-output name=annotations::$result
      - name: print
        if: ${{ failure() }}
        run: |
          echo ${{ toJson(steps.vars.outputs.annotations) }}
          
          echo "====="
          echo ${{ steps.vars.outputs.annotations }}
          echo "===sha==="
          echo ${{ github.sha }}
      - name: ktlint check-runs
        if: ${{ failure() }}
        uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: "ktlint check-runs"
          head_sha: ${{ github.sha }}
          conclusion: "failure"
          status: "completed"
          output: |
            title: "Kotlint"
            summary: ${{ toJson(steps.vars.outputs.annotations) }}
            annotations: ${{ steps.vars.outputs.annotations }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
