name: ktlintCheck
on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ (github.event.pull_request.head.sha != null && github.event.pull_request.head.sha) || github.sha }}
    outputs:
      output1: ${{ steps.vars.outputs.diff }}
      output2: ${{ steps.vars.outputs.xml_text }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: ktlintCheck
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
      - name: ktlintFormat
        if: ${{ failure() }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintFormat
      - name: set output
        if: ${{ failure() }}
        id: vars
        run: |
          echo ::set-output name=diff::$(git diff -U0)
          echo ::set-output name=xml_text::$(find . -type f -path './build/reports/ktlint/*.xml' | xargs cat)

  check-runs:
    needs: [ main ]
    if: failure()
    runs-on: ubuntu-latest
    env:
      DIFF: ${{ needs.main.vars.outputs.diff }}
      XML_TEXT: ${{ needs.main.vars.outputs.xml_text }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache main.kts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/main.kts.compiled.cache
          key: ${{ hashFiles('**/*.main.kts') }}
      - name: set output
        id: vars
        run: |
          echo "====="
          echo '${{ toJson(needs) }}'
          echo "====="
          echo ::set-output name=annotations::$(${{ env.DIFF }})
      - name: ktlint check-runs
        uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: "ktlint check-runs"
          head_sha: ${{ env.SHA }}
          conclusion: "failure"
          status: "completed"
          output: |
            title: "Ktlint"
            summary: ${{ toJson(needs.main.vars.outputs.annotations) }}
            annotations: ${{ needs.main.vars.outputs.annotations }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
