name: deploy app distribution
on:
  workflow_call:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: set
        id: vars
        run: |
          echo ::set-output name=html::$(cat << EOS
          <table>
          <tr>
          <td>Firebase Version</td>
          <td>hogehoge</td>
          </tr>
          </table>
          EOS
          )
      - uses: octokit/request-action@v2.x
        id: check_runs
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: "Result Dashboard"
          head_sha: ${{ github.sha }}
          output: |
            title: Summary
            summary: ${{ steps.vars.outputs.html }}  
            status: completed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
