name: deploy app distribution
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
#      - name: assembleRelease
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: assembleRelease -x lint
      - run: |
          echo "1.1.0" > ~/version.txt
      - uses: actions/upload-artifact@v3
        with:
          name: app distribution version
          path: /version.txt