on:
  pull_request:
    
name: Comment main PR
jobs:
  comment:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      - name: comment
        uses: octokit/request-action@v2.x
        with:
          route: POST ${{ github.event.pull_request._links.review_comment.href }}
          body: ${{ toJSON(env.REQUEST_BODY) }}
        env:
          REQUEST_BODY: |
            test comment
          GITHUB_TOKEN: ${{ github.token }}
