on:
  pull_request:
    
name: Comment main PR
jobs:
  comment:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      - name: comment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/comments/{number}
          number: ${{ github.event.number }}
          body: ${{ toJSON(env.REQUEST_BODY) }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.pull_request.base.repo.name }}
        env:
          REQUEST_BODY: |
            test comment
          GITHUB_TOKEN: ${{ github.token }}
