name: Dependencies
on:
  pull_request
permissions:
  contents: read
jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/call_ktlint
      - uses: ./.github/workflows/call_test
