name: Dependencies
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    if: {{ github.event.label.name }} == "dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/call_ktlint
      - uses: ./.github/workflows/call_test
