name: deploy app distribution
on:
  issue_comment:
    types: [ created ]

permissions:
  contents: read

jobs:
  dist_app_distribution:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == './test' }}
    uses: ./.github/workflows/call_test.yml

