name: issue comment
on:
  issue_comment:
    types: [ created ]

jobs:
  get_branch_name:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == './distFirebase' }}
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{ fromJSON(steps.pull_request.outputs.data).head.ref }}
    steps:
      - uses: octokit/request-action@v2.x
        id: pull_request
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "test"
        env:
          BRANCH_NAME: ${{ fromJSON(steps.pull_request.outputs.data).head.ref }}
        run: |
          echo "$BRANCH_NAME"
  call_dist_firebase:
    needs: [get_branch_name]
    uses: ./.github/workflows/call_deploy_app_distribution.yml
    with:
      BRANCH_NAME: ${{ needs.get_branch_name.outputs.BRANCH_NAME }}
      COMMENT_URL: ${{ github.event.issue.issue_comment_url }}
