name: distFirebase dispatch
on:
  workflow_dispatch:
    inputs:
      FEATURE1:
        description: "FEATURE1"
        required: true
        default: false
        type: boolean

jobs:
  call_dist_firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy_app_distribution
        with:
          BRANCH_NAME: ${{ github.ref_name }}
          FEATURE1: ${{ inputs.FEATURE1 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}