name: distFirebase dispatch
on:
  workflow_dispatch:
    inputs:
      FEATURE1:
        description: "feature 1"
        required: true
        default: false
        type: boolean

jobs:
  tmp:
    runs-on: ubuntu-latest
    steps:
      - name: hoge
        env:
          TMP: ${{ toJson(github.event) }}
        run: |
          echo "$TMP"
          
  # call_dist_firebase:
  #   needs: [get_branch_name]
  #   uses: ./.github/workflows/call_deploy_app_distribution.yml
  #   with:
  #     BRANCH_NAME: ${{ needs.get_branch_name.outputs.BRANCH_NAME }}

