name: issue comment
on:
  issue_comment:
    types: [ created ]

permissions:
  contents: read

jobs:
  test:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == './distFirebase' }}
    uses: ./github/workflows/call_deploy_app_distribution.yml

