name: dispatch make release pull request
on:
  workflow_dispatch:
    inputs:
      IS_UPDATE_PATCH_VERSION:
        description: "Update Pathch Version"
        default: true
        required: true
        type: boolean
      IS_UPDATE_VERSION_CODE:
        description: "Update Version Code"
        default: false
        required: true
        type: boolean

jobs:
  make_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: "update patch version"
        if: ${{ github.event.inputs.IS_UPDATE_PATCH_VERSION == 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const file = fs.readFileSync("release_info/version.json", "utf8");
            console.log(file);

            const jsonObject = JSON.parse(file);
            jsonObject.PATCH_VERSION_NAME += 1;
            fs.writeFileSync("release_info/version.json", JSON.stringify(jsonObject));
      - name: "update version code"
        if: ${{ github.event.inputs.IS_UPDATE_VERSION_CODE == 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const file = fs.readFileSync("release_info/version.json", "utf8");
            console.log(file);

            const jsonObject = JSON.parse(file);
            jsonObject.VERSION_CODE += 1;
            fs.writeFileSync("release_info/version.json", JSON.stringify(jsonObject));
      - id: version_info
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const file = fs.readFileSync("release_info/version.json", "utf8");
            console.log(file);

            core.setOutput("version_info",  fs.readFileSync("release_info/version.json", "utf8"));
      - run: |
          echo '${{ toJSON(github) }}'
      - name: "make pull request"
        run: |
          versionCode='${{ fromJson(steps.version_info.outputs.version_info).VERSION_CODE }}'
          major='${{ fromJson(steps.version_info.outputs.version_info).MAJOR_VERSION_NAME }}'
          minor='${{ fromJson(steps.version_info.outputs.version_info).MINOR_VERSION_NAME }}'
          patch='${{ fromJson(steps.version_info.outputs.version_info).PATCH_VERSION_NAME }}'
          echo $major
          echo $minor
          echo $patch
          branchName="release/${major}.${minor}.${patch}"
          git branch $branchName
          git switch $branchName
          git status
          git add "release_info/version.json"
          git commit -m "release ${major}.${minor}.${patch} v${versionCode}"
          git status
