name: dispatch make release pull request
on:
  workflow_dispatch:
    inputs:
      IS_UPDATE_PATCH_VERSION:
        description: "Update Pathch Version"
        default: true
        required: true
        type: boolean
      IS_UPDATE_VERSION_CODE:
        description: "Update Version Code"
        default: false
        required: true
        type: boolean

jobs:
  make_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: "update patch version"
        if: ${{ github.event.inputs.IS_UPDATE_PATCH_VERSION == 'true' }}
        run: | 
          echo "IS_UPDATE_PATCH_VERSION"
      - name: "update version code"
        if: ${{ github.event.inputs.IS_UPDATE_VERSION_CODE == 'true' }}
        run: | 
          echo "IS_UPDATE_VERSION_CODE"
      - id: version_info
        uses: actions/github-script@v6
        with:
          script: |
            core.setOutput("name", "test/ntest")
      - name: "make pull request"
        run: |
          echo ${{ steps.version_info.outputs.name }}
