name: merge_test
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    if: ${{ github.run_attempt != 1 }}
    uses: ./.github/workflows/call_test.yml
  lint:
    if: ${{ github.run_attempt != 1 }}
    uses: ./.github/workflows/call_ktlint.yml
  tmp:
    runs-on: ubuntu-latest
    steps:
      - name: set
        id: vars
        run: |
          echo ::set-output name=html::$(cat << EOS
          <table>
          <tr>
          <td>Firebase Version</td>
          <td>hogehoge</td>
          </tr>
          </table>
          EOS
          )
      - uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: "Result Dashboard"
          head_sha: ${{ github.sha }}
          conclusion: "success"
          status: "completed"
          external_id: "tmp"
          output: |
            title: Summary
            summary: ${{ steps.vars.outputs.html }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary": "hogehoge" }
