name: merge_test
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    if: ${{ github.run_attempt != 1 }}
    uses: ./.github/workflows/call_test.yml
  lint:
    if: ${{ github.run_attempt != 1 }}
    uses: ./.github/workflows/call_ktlint.yml
  tmp:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "===sha==="
          echo ${{ github.sha }}
