name: merge_test
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
#    if: ${{ github.run_attempt != 1 }}
    uses: ./.github/workflows/call_test.yml
  lint:
#    if: ${{ github.run_attempt != 1 }}
    uses: ./.github/workflows/call_ktlint.yml
  tmp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 1
        run: |
          echo ${TEST_TOKEN}
      - name: 1
        env:
          TEST_TOKEN: ${{ env.TEST_TOKEN }}
        run: |
          echo ${TEST_TOKEN}
