name: merge_test
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/call_test.yml
  lint:
    uses: ./.github/workflows/call_ktlint.yml
  hoge:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.run_attempt }}
