name: merge_test
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    if: ${{ github.run_attempt != 1 }}
    uses: ./.github/workflows/call_test.yml
  lint:
    if: ${{ github.run_attempt != 1 }}
    uses: ./.github/workflows/call_ktlint.yml
