name: Dist PlayStore
on:
  push:
    branches:    
      - 'main'

jobs:
  dist_play_store:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - run: ./gradlew
