name: Test
on:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run Script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMENT_URL: ${{ github.event.pull_request.comments_url }}
      run: |
        ./gradlew assembleRelease
        ./gradlew lintRelease
        ./gradlew testReleaseUnitTest
